### ISSUE TITLE
1.4.2 + xenForo 1.5.2

### ISSUE THREAD

**Issue by Sudrien** [CleanTalk/xenforo-antispam#9]
When installing the addon-CleanTalk.xml, I get a

> Error
> Line 22: Template syntax error.

I believe this is due to the  &lt;xen:option&gt; on line 9 not being closed properly.

**Comment by CleanTalk** [comment]
Hello!
Sorry for this issue!
We fixed it in version 1.4.3, try it!

**Comment by Sudrien** [comment]
1.4.3 Fixed the installation issue. Thank you!

**Comment by CleanTalk** [comment]
Thank you a lot for feedback!
